# Generated by Django 4.0.4 on 2022-06-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpages', '0002_alter_userformfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=254, verbose_name='Placeholder'),
        ),
    ]
