# Generated by Django 4.0.4 on 2022-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpages', '0003_userformfield_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformfield',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='help text'),
        ),
    ]
