# Generated by Django 4.1.7 on 2023-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpages', '0005_alter_customformsubmission_form_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformfield',
            name='heading',
            field=models.CharField(blank=True, help_text='A standalone heading displayed above this field.', max_length=254, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='userformfield',
            name='css_classes',
            field=models.CharField(blank=True, help_text='Additional CSS classes, space separated. See docs for usage hints.', max_length=255, verbose_name='CSS class names'),
        ),
        migrations.AlterField(
            model_name='userformfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='This short placeholder is displayed in the input field before the user enters a value.', max_length=254, verbose_name='Placeholder'),
        ),
    ]
