# Generated by Django 5.1.4 on 2025-01-16 10:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formpages', '0006_userformfield_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformfield',
            name='help_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='help text'),
        ),
    ]
