# Generated by Django 6.0.3 on 2026-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpages', '0008_formpage_allowed_document_file_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='allowed_document_file_types',
            field=models.CharField(default='.pdf, .txt, .docx', help_text="Comma separated list of allowed file types for document uploads. E.g. 'pdf, docx'.", max_length=255),
        ),
    ]
