# Generated by Django 6.0.5 on 2026-07-28 13:46

import wagtail_api_forms.formpages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpages', '0010_alter_formpage_allowed_document_file_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='allowed_document_file_types',
            field=models.CharField(default=wagtail_api_forms.formpages.models.default_document_file_types, help_text="Comma separated list of allowed file extensions for document uploads. Each one needs its leading dot. E.g. '.pdf, .docx'.", max_length=255),
        ),
    ]
