services:
  clamav:
    # image: docker.io/clamav/clamav:stable
    build:
      context: .
      dockerfile: Dockerfile.clamav
    container_name: clamav
    restart: unless-stopped
    ports:
      - "127.0.0.1:3310:3310"
    tty: true
    # environment:
    #   - CLAMD_CONF_FILE=/mnt/clamd.conf
    volumes:
      - clamd_data:/var/lib/clamav
  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - clamav
volumes:
  clamd_data:
    driver: local
