# Generated by Django 3.2.9 on 2021-11-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211129_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlinks',
            options={'verbose_name': 'Footer links', 'verbose_name_plural': 'Footer links'},
        ),
    ]
