# Generated by Django 4.1.7 on 2023-03-23 15:41

from django.db import migrations, models
import wagtail_api_forms.home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_brandingsettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='brand_figurative_mark',
            field=models.FileField(blank=True, help_text='Figurative mark. Format: SVG.', null=True, upload_to='branding/', validators=[wagtail_api_forms.home.models.validate_logo_image_file_extension], verbose_name="Figurative mark ('Bildmarke')"),
        ),
    ]
