# Generated by Django 4.1.7 on 2023-03-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_brandingsettings_brand_figurative_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandingsettings',
            name='site',
        ),
    ]
