# Generated by Django 4.1.7 on 2023-04-07 21:51

from django.db import migrations, models
import wagtail_api_forms.home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_brandingsettings_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='branding_css_variables',
            field=models.JSONField(default=wagtail_api_forms.home.models.BrandingSettings.branding_css_variables_default_json, help_text='\n            CSS variables to tweak the styling. Expects a dictionary \n            (JSON formatted) with at least values for the keys\n            `primary_accent_color` and `primary_accent_gray`.\n        ', verbose_name='CSS Variables'),
        ),
    ]
