# Generated by Django 4.2.3 on 2023-07-24 11:42

from django.db import migrations, models
import wagtail.images.models
import wagtail_api_forms.home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_brandingsettings_branding_css_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsettings',
            name='branding_css_variables',
            field=models.JSONField(default=wagtail_api_forms.home.models.BrandingSettings.branding_css_variables_default_json, help_text='\n            CSS variables to tweak the styling. Expects a dictionary \n            (JSON formatted) with at least values for the keys\n            `primary_accent_color` `primary_accent_color_darken` and `primary_accent_gray`.\n        ', verbose_name='CSS Variables'),
        ),
        migrations.AlterField(
            model_name='customrendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
