# Generated by Django 5.0.1 on 2024-01-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_brandingsettings_branding_css_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='show_admin_link_for_ips',
            field=models.CharField(blank=True, help_text='Display admin link in footer for given IP addresses. Separate multiple IPs with commas. Subnets allowed.', max_length=255, verbose_name='Show admin link for IPs'),
        ),
    ]
