# Generated by Django 5.1.4 on 2025-01-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customimage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='description',
        ),
        migrations.AlterField(
            model_name='customdocument',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
